services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

