spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_app?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USERNAME}
    password: ${ENV_MYSQL_ROOT_PASSWORD}
  threads:
    virtual:
      enabled: true
  application:
    name: to-do-app
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

