spring:
  threads:
    virtual:
      enabled: true
  application:
    name: to-do-app
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

